export const artifacts = [
  {
    id: 1,
    name: "Akhenaten",
    kingdom: "New Kingdom",
    material: "Sandstone",
    image: "/images/Akhenaten.webp",
    modelPath: "/models/akhenaten.glb",
    audioPath: "/audios/Akhenatenfinale.mpeg",
    modelScale: 1.9,
        modelPosition: [0, -1.3, 0],
    description: "I am Akhenaten.. A king who changed everything, one God, one truth.. I am not just history, I am change.",
    timestamps: [],
    hotspots: [
      {
        id: "head",
        position: [0.1, 0.809, 0.028],
        title: "Elongated Head",
        description: "The unusually long skull was a deliberate artistic choice of the Amarna period, reflecting a new aesthetic canon introduced under Akhenaten's reign.",
        cameraPosition: [0.1, 0.809, 1.5],
        cameraTarget: [0.1, 0.809, 0.028],
      },
      {
        id: "face",
        position: [-0.235, -0.712, 0.608],
        title: "Facial Features",
        description: "The narrow almond eyes, high cheekbones and full lips break from traditional Egyptian idealism — showing the king as a spiritual being rather than a perfect ruler.",
        cameraPosition: [-0.235, -0.712, 1.5],
        cameraTarget: [-0.235, -0.712, 0.608],
      },
      {
        id: "crown",
        position: [-0.256, -0.266, 0.576],
        title: "Royal Crown",
        description: "The Khepresh, or Blue War Crown, was worn during religious ceremonies and battles. Its deep blue color symbolized the sky and the power of the sun god Aten.",
        cameraPosition: [-0.256, -0.266, 1.5],
        cameraTarget: [-0.256, -0.266, 0.576],
      },
    ],
  },
  {
    id: 2,
    name: "Khafre",
    kingdom: "Old Kingdom",
    material: "Anorthosite Gneiss",
    image: "/images/Khafre.webp",
    description: "Do not stand before me as if I am ordinary, I am Khafre.. king of Egypt, builder of the second pyramid.. you may come and go but I remain.",
    audioPath: "/audios/Khafrefinale.mpeg",
    modelPath: "/models/khafrev2.glb",
    modelScale: 1.5,
    modelPosition: [0, -1.5, 0],
hotspots: [
  {
    id: "face",
    position: [-0.0063, 1.4114, -0.0309],
    title: "Royal Face",
    description: "The serene expression of Khafre reflects divine calm — pharaohs were depicted as eternally composed, embodying the stability of the Egyptian cosmos.",
    cameraPosition: [-0.021, 1.103, 1.2],
    cameraTarget: [-0.021, 1.103, -0.046],
  },
  {
    id: "beard",
    position: [-0.0081, 1.3011, -0.0041],
    title: "Royal Beard",
    description: "The ceremonial false beard was a symbol of divine kingship, worn by pharaohs to identify themselves with the god Osiris.",
    cameraPosition: [-0.006, 0.951, 1.2],
    cameraTarget: [-0.006, 0.951, -0.007],
  },
  {
    id: "nemes",
    position: [-0.0955, 1.3162, -0.1245],
    title: "Nemes Headdress",
    description: "The nemes is the striped linen cloth worn exclusively by pharaohs. Its two front flaps fall over the chest while the back is tied into a tail.",
    cameraPosition: [-0.176, 1.043, 0.8],
    cameraTarget: [-0.176, 1.043, -0.215],
  },
  {
    id: "fist",
    position: [-0.1230, 0.9605, 0.1567],
    title: "Clenched Fist",
    description: "The clenched fist holds a folded cloth — a symbol of royal power and control. This gesture appears consistently in Old Kingdom royal sculpture.",
    cameraPosition: [-0.180, 0.438, 1.2],
    cameraTarget: [-0.180, 0.438, 0.239],
  },
  {
    id: "openhand",
    position: [0.0775, 0.8998, 0.1959],
    title: "Open Hand",
    description: "The open flat hand resting on the knee symbolizes receptiveness and divine authority — a posture of a ruler ready to receive offerings.",
    cameraPosition: [0.117, 0.359, 1.2],
    cameraTarget: [0.117, 0.359, 0.278],
  },
  {
    id: "throne",
    position: [0.0077, 0.5784, -0.2658],
    title: "Throne Back",
    description: "The sides of the throne bear the sema-tawy symbol — the unification of Upper and Lower Egypt, depicted as lotus and papyrus plants tied together.",
    cameraPosition: [-0.020, -0.147, -1.8],
    cameraTarget: [-0.020, -0.147, -0.393],
  },
  {
    id: "kilt",
    position: [0.1582, 0.8552, -0.0590],
    title: "Royal Kilt",
    description: "The shendyt kilt was the traditional royal garment of ancient Egypt, worn during ceremonial occasions to signify the pharaoh's status.",
    cameraPosition: [0.234, 0.317, 0.9],
    cameraTarget: [0.234, 0.317, -0.138],
  },
],     
}, 
  {
    id: 3,
    name: "Ramessesnakht",
    kingdom: "New Kingdom",
    material: "Granite",
    image: "/images/High_Priest_Ramessesnakht.webp",
     audioPath: "/audios/Hightpriestfinale.mpeg",
     description:"Not a King, not a worrier. I am Ramessesnakht, High priest of Amun, my power was a word spoken in sacred spaces and words never die.",
    modelPath: "/models/ramessesnakhtv2.glb",
    modelScale: 1.8,
    modelPosition: [0, -1.0, 0],
    hotspots: [
    {
      id: "papyrus_lap",
      position: [-0.088, -0.399, 0.190],
      title: "Papyrus on Lap",
      description: "A sacred papyrus scroll rests on his lap — a symbol of priestly knowledge and ritual authority. High priests were the keepers of divine texts and temple ceremonies.",
  cameraPosition: [-0.426, 0.5, 1.2], 
        cameraTarget: [-0.088, -0.399, 0.190],
    },
    {
      id: "scroll",
      position: [0.162, -0.326, 0.110],
      title: "Sacred Scroll",
      description: "Ramessesnakht holds a rolled papyrus scroll — representing his role as the highest religious authority in Egypt, responsible for performing the most sacred rites.",
      cameraPosition: [0.162, -0.326, 1.2],
      cameraTarget: [0.162, -0.326, 0.110],
    },
    {
      id: "baboon",
      position: [-0.015, 0.732, -0.100],
      title: "Baboon of Thoth",
      description: "A baboon sits atop his head — the sacred animal of Thoth, god of wisdom and writing. This rare detail identifies Ramessesnakht as a scribe-priest of the highest order.",
      cameraPosition: [-0.015, 0.732, 1.0],
      cameraTarget: [-0.015, 0.732, -0.100],
    },
    {
      id: "belly",
      position: [-0.058, -0.192, -0.046],
      title: "Aged Belly",
      description: "The soft, rounded abdomen is a deliberate artistic choice — unlike the idealized young bodies of royal statues, this marks Ramessesnakht as a man of wisdom, age, and high status.",
      cameraPosition: [-0.058, -0.192, 1.2],
      cameraTarget: [-0.058, -0.192, -0.046],
    },
    {
      id: "seat_inscription",
      position: [0.004, -0.840, 0.391],
      title: "Seat Inscription",
      description: "Hieroglyphic inscriptions carved into the seat record his titles, lineage, and dedications to the gods — a permanent record of his divine service.",
      cameraPosition: [0.004, -0.840, 1.2],
      cameraTarget: [0.004, -0.840, 0.391],
    },
    {
      id: "garment",
      position: [-0.291, -0.017, -0.155],
      title: "Priestly Garment",
      description: "The long linen robe is the ceremonial dress of a high priest. Its fine folds indicate wealth and sacred status — only the highest officials wore garments of such quality.",
      cameraPosition: [-0.291, -0.017, 0.9],
      cameraTarget: [-0.291, -0.017, -0.155],
    },
    {
      id: "leg_inscription",
      position: [-0.426, -0.522, 0.229],
      title: "Leg Inscription",
      description: "Additional hieroglyphs carved along his leg list his many priestly titles — including High Priest of Amun, the most powerful religious position in New Kingdom Egypt.",
       cameraPosition: [-1.5, -0.522, 0.229], 
      cameraTarget: [-0.426, -0.522, 0.229],
    },
    {
      id: "face",
      position: [0.029, 0.374, 0.061],
      title: "Facial Features",
      description: "The realistic face shows signs of age — deep-set eyes, pronounced cheekbones, and a calm authoritative expression befitting one of ancient Egypt's most powerful priests.",
      cameraPosition: [0.029, 0.374, 1.0],
      cameraTarget: [0.029, 0.374, 0.061],
    },
  ],
},
  {
    id: 4,
    name: "God Serapis",
    kingdom: "Greco-Roman Period",
    material: "Egyptian Alabaster",
    image: "/images/God_Serapis.webp",
     audioPath: "/audios/Serapisfinale.mpeg",
     description: "Empires rose and fell before me. I am Serapis. Where Egypt and Greece became one! I remain.",
    modelPath: "/models/godserapisv2.glb",
    modelScale: 1.8,
    modelPosition: [0, -2.7, 0.2],
     hotspots: [
    {
      id: "face",
      position: [0.298, 0.701, 0.312],
      title: "Face of Serapis",
      description: "The face of Serapis blends Greek and Egyptian traditions — combining the majestic features of Zeus with the divine authority of Osiris, reflecting the Greco-Roman rule of Egypt.",
cameraPosition: [1.5, 0.701, 0.312],  // ← x موجب عشان من اليمين
cameraTarget: [0.298, 0.701, 0.312],
    },
    {
      id: "beard",
      position: [0.286, 0.497, 0.292],
      title: "Divine Beard",
      description: "The long, wavy beard is characteristic of both Greek gods and Egyptian deities. For Serapis, it signifies his role as a god of the afterlife, fertility, and the underworld.",
    cameraPosition: [1.5, 0.497, 0.292],  // ← x موجب عشان من اليمين
cameraTarget: [0.286, 0.497, 0.292],
    },
    {
      id: "garment",
      position: [0.236, -0.082, 0.233],
      title: "Draped Garment",
      description: "The flowing robes reflect Hellenistic artistic influence — a Greek-style himation draped over the body, distinguishing Serapis from purely Egyptian deities.",
      cameraPosition: [1.5, -0.082, 0.233],  // ← x موجب عشان من اليمين
cameraTarget: [0.236, -0.082, 0.233],
    },
    {
      id: "missing_hand",
      position: [0.094, -0.010, 0.760],
      title: "Missing Hand",
      description: "The absence of the hand speaks to centuries of history — this fracture occurred long after the statue's creation, a reminder of the fragility of ancient treasures.",
      cameraPosition: [0.094, -0.010, 1.5],
      cameraTarget: [0.094, -0.010, 0.760],
    },
  ],
},
  {
    id: 5,
    name: "Hor Son Of Hor",
    kingdom: "Ptolemaic Period",
    material: "Granite",
    image: "/images/Hor_Son_Hor.webp",
     audioPath: "/audios/Horsonofhorfinale.mpeg",
     description: "I am Hor son of Hor a priest of thoughts from the late Ptolemaic period. You can see it in how.. I'm made there's balance, but also.. something different.",
    modelPath: "/models/horsonhorv2.glb",
    modelScale: 2.5,
    modelPosition: [0, -2.1, 0],
     hotspots: [
    {
      id: "face",
      position: [0.025, 0.841, 0.205],
      title: "Face of Hor",
      description: "The face reflects the Ptolemaic style — a blend of Egyptian tradition and Hellenistic influence, with softer features and a serene expression characteristic of the late period.",
      cameraPosition: [0.025, 0.841, 1.3],
      cameraTarget: [0.025, 0.841, 0.205],
    },
    {
      id: "garment",
      position: [0.107, 0.037, 0.181],
      title: "Garment",
      description: "The tightly wrapped linen garment follows traditional Egyptian funerary dress, indicating Hor's status as a sacred official during the Ptolemaic dynasty.",
      cameraPosition: [0.107, 0.037, 1.3],
      cameraTarget: [0.107, 0.037, 0.181],
    },
    {
      id: "fist",
      position: [0.081, -0.622, 0.295],
      title: "Clenched Fist",
      description: "The clenched fist held at the side is a gesture of strength and divine readiness — commonly seen in Egyptian votive statues presented to temples as offerings.",
      cameraPosition: [0.081, -0.622, 1.3],
      cameraTarget: [0.081, -0.622, 0.295],
    },
    {
      id: "pillar_inscription",
      position: [0.033, 0.613, -0.310],
      title: "Pillar Inscription",
      description: "The back pillar bears hieroglyphic texts naming Hor and his father, listing their titles and dedications to the gods — a permanent record of their sacred lineage.",
      cameraPosition: [0.033, 0.613, -1.5],
      cameraTarget: [0.033, 0.613, -0.310],
    },
  ],
},
  {
    id: 6,
    name: "Scribe Statue",
    kingdom: "Middle Kingdom",
    material: "Limestone",
    image: "/images/Scribe_Statue.webp",
    modelPath: "/models/scribestatuev2.glb",
     audioPath: "/audios/Scribefinale.mpeg",
     description: "I am a Scribe, not a King, not a God, yet i endured. I did not build monuments, I wrote and what is written, remains.",
    modelScale: 3.0,
    modelPosition: [-0.3, -3.5, 0],
     hotspots: [
    {
      id: "belly",
      position: [-0.333, 0.118, 0.402],
      title: "Rounded Belly",
      description: "The soft, prominent belly is a hallmark of Egyptian scribe statues — far from an imperfection, it signifies wealth, sedentary intellectual work, and high social status.",
      cameraPosition: [-0.333, 0.118, 1.3],
      cameraTarget: [-0.333, 0.118, 0.402],
    },
    {
      id: "papyrus_lap",
      position: [-0.454, -0.144, 0.750],
      title: "Papyrus on Lap",
      description: "An unrolled papyrus scroll rests across his crossed legs — the defining attribute of a royal scribe, ready to record the words of officials, priests, and pharaohs.",
       cameraPosition: [-0.454, 1.2, 0.750],  // ← y لفوق
  cameraTarget: [-0.454, -0.144, 0.750],
    },
    {
      id: "face",
      position: [-0.340, 0.782, 0.554],
      title: "Broken Nose",
      description: "The broken nose is a common result of ancient vandalism or time — in Egyptian belief, damaging a statue's face could destroy its spiritual power, so enemies often targeted the nose deliberately.",
      cameraPosition: [-0.340, 0.782, 1.3],
      cameraTarget: [-0.340, 0.782, 0.554],
    },
    {
      id: "scroll",
      position: [-0.087, -0.013, 0.753],
      title: "Scroll in Hand",
      description: "The tightly held papyrus roll symbolizes the scribe's mastery of writing — one of the most prestigious skills in ancient Egypt, mastered by only a small educated elite.",
      cameraPosition: [-0.087, -0.013, 1.5],
      cameraTarget: [-0.087, -0.013, 0.753],
    },
    {
      id: "kilt",
      position: [0.133, -0.280, 0.442],
      title: "Scribal Kilt",
      description: "The white linen kilt stretched tightly across the crossed legs forms a flat writing surface — scribes would often use their lap as a desk, with the kilt acting as a portable writing board.",
      cameraPosition: [1.5, -0.280, 0.442],  // ← x موجب عشان من اليمين
cameraTarget: [0.133, -0.280, 0.442],
    },
  ],
},
  {
    id: 7,
    name: "Khakaureseneb",
    kingdom: "Middle Kingdom",
    material: "Quartzite",
    image: "/images/Khakaureseneb.webp",
     audioPath: "/audios/Khakauresenebfinale.mpeg",
    modelPath: "/models/Khakauresenebv2.glb",
    description: "To understand me, just look. I am Khakaureseneb of the middle Kingdom. Not a king but my face is real, and so is my story.",
    modelScale: 0.9,
    modelPosition: [-0.5, -1.0, 0],
      hotspots: [
    {
      id: "face",
      position: [0.185, 1.562, 0.493],
      title: "Face of Khakaureseneb",
      description: "The realistic, individualized face is characteristic of Middle Kingdom portraiture — unlike the idealized faces of the Old Kingdom, this style captures the humanity and wisdom of the subject.",
      cameraPosition: [1.5, 1.562, 0.493],  // ← x موجب عشان من اليمين
cameraTarget: [0.185, 1.562, 0.493],
    },
    {
      id: "kilt_detail",
      position: [0.215, 0.538, 0.673],
      title: "Kilt Detail",
      description: "The finely pleated kilt is a mark of elite status in ancient Egypt. The intricate folds required skilled linen work, accessible only to high-ranking officials and priests.",
      cameraPosition: [1.5, 0.538, 0.673],  // ← x موجب عشان من اليمين
cameraTarget: [0.215, 0.538, 0.673],
    },
    {
      id: "knee_inscription",
      position: [0.763, 0.089, 0.614],
      title: "Knee Inscription",
      description: "Hieroglyphic texts carved on the knee area record prayers and dedications to the gods — ensuring that the statue would serve as an eternal intercessor in the temple.",
      cameraPosition: [0.763, 1.5, 0.614],  // ← y لفوق
cameraTarget: [0.763, 0.089, 0.614],
    },
    {
      id: "chair_inscription",
      position: [1.207, -0.496, 0.672],
      title: "Chair Inscription",
      description: "The inscriptions on the chair sides list Khakaureseneb's titles and family lineage — a permanent record carved in stone to preserve his identity and status for eternity.",
      cameraPosition: [2.0, 0.5, 1.5],  // ← x من اليمين + y شوية فوق + z قدام = زاوية 45
cameraTarget: [1.207, -0.496, 0.672],
    },
    {
      id: "chair_back",
      position: [-0.481, 0.496, 0.758],
      title: "Chair Back",
      description: "The back of the chair bears additional religious texts — prayers to Osiris and Ptah asking for offerings of bread, beer, and linen for the eternal sustenance of the deceased.",
      cameraPosition: [-1.5, 0.496, 0.758],  // ← x موجب عشان من اليمين
cameraTarget: [-0.481, 0.496, 0.758],
    },
    {
      id: "hair",
      position: [-0.182, 1.424, 0.100],
      title: "Hair & Wig",
      description: "The short rounded wig was standard elite attire in the Middle Kingdom. Made from human hair or plant fibers, wigs were symbols of cleanliness and social refinement.",
      cameraPosition: [1.5, 1.424, 0.100],  // ← x موجب عشان من اليمين
cameraTarget: [-0.182, 1.424, 0.100],
    },
  ],
},
];